export const RENDER_RESULTS = 'RENDER_RESULTS';
export const SET_INCOME = 'SET_INCOME';
export const SET_PENSION = 'SET_PENSION';
export const SET_PENSION_TYPE = 'SET_PENSION_TYPE';
export const SET_UNDERGRAD_LOAN = 'SET_UNDERGRAD_LOAN';
export const SET_POSTGRAD_LOAN = 'SET_POSTGRAD_LOAN';
export const SET_EXTRA_INPUT = 'SET_EXTRA_INPUT';